# comment
merge:
  sourceDirectory: dxf/blocks
  targetDirectory: dxf
  default:
    6mm_plywood_cut_left_right.dxf:
      6mm_les_izrez_levo - LM8UU.dxf:
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
      6mm_les_izrez_desno - LM8UU.dxf:
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
    6mm_plywood_cut_front_back.dxf:
      6mm_les_izrez_spredaj - LM8UU.dxf:
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
      6mm_les_izrez_zadaj - LM8UU.dxf: None
    6mm_plywood_cut_top_bottom.dxf:
      6mm_les_izrez_gor - LM8UU.dxf:
        move: [-206.0, 205.0]
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
      6mm_les_izrez_dol - LM8UU.dxf:
        move: [206.0, 205.0]
    6mm_plexi_cut_windows.dxf:
      6mm_les_izrez_gor - LM8UU.dxf:
        ignoreLayers:
        - HOLES
        - IZREZ
        renameLayers:
          IZREZ_PLEXI: IZREZ
          HOLES_PLEXI: HOLES