merge:
  sourceDirectory: dxf/blocks
  targetDirectory: dxf
  default:
    6mm_plywood_cut_left_right.dxf:
      6mm_les_izrez_levo - LM8UU.dxf:
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
      6mm_les_izrez_desno - LM8UU.dxf:
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
    6mm_plywood_cut_front_back.dxf:
      6mm_les_izrez_spredaj - LM8UU.dxf:
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
      6mm_les_izrez_zadaj - LM8UU.dxf: None
    6mm_plywood_cut_top_bottom.dxf:
      6mm_les_izrez_gor - LM8UU.dxf:
        move: [-206.0, 205.0]
        ignoreLayers:
        - HOLES_PLEXI
        renameLayers:
          IZREZ_PLEXI: IZREZ
      6mm_les_izrez_dol - LM8UU.dxf:
        move: [206.0, 205.0]
    6mm_plexi_cut_windows.dxf:
      6mm_les_izrez_gor - LM8UU.dxf:
        ignoreLayers:
        - HOLES
        - IZREZ
        renameLayers:
          IZREZ_PLEXI: IZREZ
          HOLES_PLEXI: HOLES

solidify:
  sourceDirectory: dxf/blocks
  targetDirectory: stl
  cutLayer: IZREZ
  groups:
    printer:
      6mm_les_izrez_gor - LM8UU.dxf:
        save: movedTOP.stl
        modifications:
          - extrude: 6.0
          - translate: [.0, .0, 478.0]
      6mm_les_izrez_dol - LM8UU.dxf:
        save: movedBOTTOM.stl
        modifications:
          - extrude: 6.0
          - rotate: [math.pi, [.0, 1.0, .0], [.0, .0, .0]]
          - translate: [.0, .0, 80.0]
      6mm_les_izrez_levo - LM8UU.dxf:
        save: movedLEFT.stl
        modifications:
          - extrude: 6.0
          - rotate: [math.pi/2, [.0, .0, 1.0], [.0, .0, .0]]
          - rotate: [math.pi/2, [.0, 1.0, .0], [.0, .0, .0]]
          - translate:  [-205.0, 211.0, .0]
      6mm_les_izrez_desno - LM8UU.dxf:
        save: movedRIGHT.stl
        modifications:
          - extrude: 6.0
          - rotate: [-math.pi/2, [.0, .0, 1.0], [.0, .0, .0]]
          - rotate: [-math.pi/2, [.0, 1.0, .0], [.0, .0, .0]]
          - translate:  [205.0, 211.0, .0]
      6mm_les_izrez_spredaj - LM8UU.dxf:
        save: movedFRONT.stl
        modifications:
          - extrude: 6.0
          - rotate: [math.pi / 2, [1.0, .0, .0], [.0, .0, .0]]
          - translate: [209.0, -198.0, .0]
      6mm_les_izrez_zadaj - LM8UU.dxf:
        save: movedBACK.stl
        modifications:
          - extrude: 6.0
          - rotate: [math.pi / 2, [1.0, .0, .0], [.0, .0, .0]]
          - translate: [-209.0, 205.0, .0]
    hotEnd:
      6mm_les_izrez_hotend_top.dxf:
        save: movedHE_TOP.stl
        modifications:
          - extrude: 6.0
          - translate: [0.0, 0.0, 16.0]
      6mm_les_izrez_hotend_bottom.dxf:
        save: movedHE_BOTTOM.stl
        modifications:
          - extrude: 6.0
          - translate: [0.0, 0.0, -22.0]
      6mm_les_izrez_hotend_side_7.dxf:
        save: movedHE_FRONT.stl
        modifications:
          - extrude: 6.0
          - rotate: [math.pi / 2, [1.0, .0, .0], [.0, .0, .0]]
          - translate: [0.0, -7.0, 0.0]
      6mm_les_izrez_hotend_side_7.dxf:
        save: movedHE_BACK.stl
        modifications:
          - extrude: 6.0
          - rotate: [math.pi / 2, [1.0, .0, .0], [.0, .0, .0]]
          - translate: [0.0, 13.0, 0.0]
      6mm_les_izrez_hotend_side_7.dxf:
        save: movedHE_LEFT.stl
        modifications:
          - extrude: 6.0
          - rotate: [-math.pi / 2, [.0, .0, 1.0], [.0, .0, .0]]
          - rotate: [math.pi / 2, [.0, 1.0, .0], [.0, .0, .0]]
          - translate: [-13.0, 0.0, 0.0]
      6mm_les_izrez_hotend_side_7.dxf:
        save: movedHE_RIGHT.stl
        modifications:
          - extrude: 6.0
          - rotate: [-math.pi / 2, [.0, .0, 1.0], [.0, .0, .0]]
          - rotate: [math.pi / 2, [.0, 1.0, .0], [.0, .0, .0]]
          - translate: [7.0, 0.0, 0.0]
    table:
      6mm_les_izrez_miza.dxf:
        save: movedTABLE.stl
        modifications:
          - extrude: 6.0
          - translate: [0.0, 0.0, 200.0]
